package_path: "assets-compiled"

javascripts:
  script:
    - public/javascripts/jquery/jquery.js
    - public/javascripts/jquery/iphoneStyle.js
    - public/javascripts/default.js

stylesheets:
  styles:
    - public/stylesheets/compiled/style.css