default: features --format pretty --color --tags ~@todo --tags ~@slow --no-source
todo: features --tags @todo
dev: features --format pretty --color --tags ~@todo
slow: features --format pretty --color --tags @slow --no-source