defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: railsgen

test:
  <<: *defaults
  database: railsgen_test

staging:
  <<: *defaults
  database: railsgen_staging

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGO_URI'] %>